jobs:
  include:
    - stage: test
      language: python
      python: 3.7
      before_script:
        - cd backend
      script:
        - python -m unittest discover
    - language: nodejs
      node_js:
        - node
      before_script:
        - cd frontend
      install:
        - yarn
    - stage: deploy
      if: branch = master
      addons:
      ssh_known_hosts: $IP_ADDR
      deploy:
      provider: script
      script: bash assets/deploy.sh
