os: linux
dist: xenial
language: shell
jobs:
  include:
  - stage: test
    language: python
    python: 3.7
    before_install:
    - cd backend
    script:
    - pip install pytest
    - python -m pytest
  - language: node_js
    cache:
      directories:
      - frontend/node_modules
    node_js:
    - node
    before_install:
    - cd frontend
    install:
    - yarn
  - stage: deploy
    if: branch = master
    deploy: 
    script: bash remote_exec.sh
    before_script:
    - cd assets
before_install:
- openssl aes-256-cbc -K $encrypted_f40348afbfb2_key -iv $encrypted_f40348afbfb2_iv
  -in assets/futurist_ci.enc -out assets/futurist_ci -d
