os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: test
      language: python
      python: 3.7
      before_script:
        - cd backend
      script:
        - python -m unittest discover
    - language: node_js
      cache:
        directories:
          - frontend/node_modules
      node_js:
        - node
      before_install:
        - cd frontend
      install:
        - yarn
    - stage: deploy
      if: branch = master
      deploy:
      script: bash remote_exec.sh
      before_script:
        - cd assets
